# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Join' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Join
  pod 'Firebase/Firestore'

  target 'JoinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JoinUITests' do
    # Pods for testing
  end

end
